<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.11" />
      <PackageReference Include="BedrockLauncher.Core" Version="2.0.4.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../BedrockBoot.Inject\BedrockBoot.Inject.csproj" />
      <ProjectReference Include="../BedrockBoot.LevelNbt\BedrockBoot.LevelNbt.csproj" />
      <ProjectReference Include="../Round.SDK\Round.SDK\Round.SDK.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Dependence\Inject.dll" />
    </ItemGroup>

</Project>
