<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>BedrockBoot</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BedrockLauncher.Core.Linux" Version="1.0.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BedrockBoot.Base\BedrockBoot.Base.csproj" />
      <ProjectReference Include="..\BedrockBoot.Core\BedrockBoot.Core.csproj" />
      <ProjectReference Include="..\BedrockBoot.Proton\BedrockBoot.Proton.csproj" />
      <ProjectReference Include="..\Round.SDK\Round.SDK\Round.SDK.csproj" />
    </ItemGroup>

</Project>
