<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <DefineConstants>WINDOWS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
        <TargetFramework>net10.0</TargetFramework>
        <DefineConstants>LINUX</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\BedrockBoot.Base\BedrockBoot.Base.csproj" />
      <ProjectReference Include="..\BedrockBoot.Core\BedrockBoot.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BedrockLauncher.Core"
                          Version="2.0.4.9"
                          Condition="$([MSBuild]::IsOSPlatform('Windows'))"/>

        <PackageReference Include="BedrockLauncher.Core.Linux"
                          Version="1.0.0.4"
                          Condition="$([MSBuild]::IsOSPlatform('Linux'))"/>
    </ItemGroup>
</Project>
