<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <TargetFrameworks>net10.0-windows10.0.19041.0;net10.0-android</TargetFrameworks>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
        <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <Authors>Round-Studio</Authors>
        <Company>Round-Studio</Company>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' != 'net10.0-android'">
        <OutputType>WinExe</OutputType>
        <Win32Resource Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">Manifest.res</Win32Resource>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
        <OutputType>Library</OutputType>
        <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
        <RuntimeIdentifier>android-x64</RuntimeIdentifier>

    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
        <UseWindowsForms>true</UseWindowsForms>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
        <BuildTimestamp>$([System.DateTime]::Now.ToString("yyyy-MM-dd HH:mm:ss"))</BuildTimestamp>
    </PropertyGroup>
    <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.GC.ConserveMemory" Value="5"/>
    <RuntimeHostConfigurationOption Include="System.GC.RetainVM" Value="false"/>
    <RuntimeHostConfigurationOption Include="System.GC.Server" Value="false"/>
    </ItemGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
            <_Parameter1>BuildTimestamp</_Parameter1>
            <_Parameter2>$(BuildTimestamp)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <Content Include="Assets\Icon\BedrockBoot.Icon.512x.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <AvaloniaResource Include="Assets\**"/>
        <AvaloniaResource Include="Manifest\Function\FunctionOption.json"/>
        <AvaloniaResource Include="Assets\Web\LoginFinish.html" />
        <AvaloniaResource Include="Assets\Text\ChangLog.txt" />
        <AvaloniaResource Include="Manifest\DefaultCustomManifest.json" />
        <Folder Include="Assets\Svg\"/>
        <AvaloniaXaml Include="I18n\**"/>
        <Folder Include="Entity\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.3"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.3" Condition="'$(TargetFramework)' != 'net10.0-android'"/>
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.3"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3"/>
        <PackageReference Include="Avalonia.HarfBuzz" Version="12.1.3" Condition="'$(TargetFramework)' != 'net10.0-android'"/>
        <PackageReference Include="Interop.IWshRuntimeLibrary" Version="1.0.1" Condition="'$(TargetFramework)' != 'net10.0-android'"/>
        <PackageReference Include="HtmlAgilityPack" Version="1.11.71"/>
        <PackageReference Include="Markdig" Version="1.2.0" />
        <PackageReference Include="NAudio" Version="2.2.1" Condition="'$(TargetFramework)' != 'net10.0-android'"/>
        <PackageReference Include="Octokit" Version="14.0.0"/>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12"/>
        <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.15" Condition="'$(TargetFramework)' != 'net10.0-android'"/>
    </ItemGroup>

<ItemGroup>
        <ProjectReference Include="..\AvaMotion\src\AvaMotion\AvaMotion.csproj" />
        <ProjectReference Include="..\BedrockBoot.Standard\BedrockBoot.Standard.csproj" />
        <ProjectReference Include="..\BedrockBoot.Chunker\BedrockBoot.Chunker.csproj"/>
        <ProjectReference Include="..\BedrockBoot.Core\BedrockBoot.Core.csproj"/>
        <ProjectReference Include="..\BedrockBoot.GravityCone\BedrockBoot.GravityCone.csproj" />
        <ProjectReference Include="..\BedrockBoot.LevelNbt\BedrockBoot.LevelNbt.csproj"/>
        <ProjectReference Include="..\BedrockBoot.MSAL\BedrockBoot.MSAL.csproj"/>
        <ProjectReference Include="..\BedrockBoot.Proton\BedrockBoot.Proton.csproj" />
        <ProjectReference Include="..\BedrockBoot.WatchDog\BedrockBoot.WatchDog.csproj" />
        <ProjectReference Include="..\LiteSkinViewer\LiteSkinViewer.2D\LiteSkinViewer.2D.csproj" />
        <ProjectReference Include="..\LiteSkinViewer\LiteSkinViewer.3D\LiteSkinViewer.3D.csproj" />
        <ProjectReference Include="..\OnePointUI.Avalonia\src\OnePointUI.Avalonia\OnePointUI.Avalonia.csproj"/>
        <ProjectReference Include="..\PaperConnect\src\PaperConnect.Core\PaperConnect.Core.csproj"/>
        <ProjectReference Include="..\ResourcePackConvert\ResourcePackConvert.Core\ResourcePackConvert.Core.csproj" />
        <ProjectReference Include="..\Round.SDK\Round.SDK.Avalonia\Round.SDK.Avalonia.csproj"/>
        <ProjectReference Include="..\Round.SDK\Round.SDK\Round.SDK.csproj"/>
        <ProjectReference Include="..\Wallpaper.Avalonia\Wallpaper.Avalonia.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BedrockBoot.Windows\BedrockBoot.Windows.csproj"
                          Condition="$([MSBuild]::IsOSPlatform('Windows')) AND '$(TargetFramework)' != 'net10.0-android'"/>

        <ProjectReference Include="..\BedrockBoot.MSAL\BedrockBoot.MSAL.csproj"
                          Condition="$([MSBuild]::IsOSPlatform('Windows'))"/>

        <ProjectReference Include="..\BedrockBoot.Linux\BedrockBoot.Linux.csproj"
                          Condition="$([MSBuild]::IsOSPlatform('Linux'))"/>
    </ItemGroup>

    <Import Project="Build/GenerateChangeLog.targets"
            Condition="'$(Configuration)' == 'Release'"/>
</Project>
