<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\Icon\BedrockBoot.Icon.512x.ico</ApplicationIcon>
		
       <LangVersion>14.0</LangVersion>
      <!-- 设置裁剪级别 -->
      <!-- 可选值：full（完全裁剪）, partial（部分裁剪）, none（不裁剪） -->
      <TrimMode>none</TrimMode>

      <!-- 启用裁剪警告，帮助识别问题 -->
      <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>

      <!-- 启用单文件分析 -->
      <EnableSingleFileAnalysis>true</EnableSingleFileAnalysis>
    </PropertyGroup>
  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <!-- Necessary before Avalonia 12.0, was used for accessiblity APIs -->
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\Icon\Minecraft\**" />
  </ItemGroup>
  <ItemGroup>
    <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
  </ItemGroup>
    <PropertyGroup>
      <BuildTimestamp>$([System.DateTime]::Now.ToString("yyyy-MM-dd HH:mm:ss"))</BuildTimestamp>
    </PropertyGroup>

    <ItemGroup>
      <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
        <_Parameter1>BuildTimestamp</_Parameter1>
        <_Parameter2>$(BuildTimestamp)</_Parameter2>
      </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AsyncImageLoader.Avalonia" Version="3.4.3" />
        <PackageReference Include="Avalonia" Version="11.3.9" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.9">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Downloader" Version="4.0.3" />
        <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
        <PackageReference Include="Octokit" Version="14.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BedrockLauncher.Core\BedrockLauncher.Core\BedrockLauncher.Core.csproj" />
      <ProjectReference Include="..\OnePointUI.Avalonia\src\OnePointUI.Avalonia\OnePointUI.Avalonia.csproj" />
      <ProjectReference Include="..\Round.SDK\Round.Avalonia.Assets\Round.Avalonia.Assets.csproj" />
      <ProjectReference Include="..\Round.SDK\Round.SDK\Round.SDK.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Windows\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\TaskItem\TaskLaunchGameItem.axaml.cs">
        <DependentUpon>DialogLaunchGameContent.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
