<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <TargetFrameworks>net10.0-windows10.0.19041.0;net10.0-android</TargetFrameworks>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
        <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
        <RuntimeIdentifier>android-x64</RuntimeIdentifier>

    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BedrockBoot.Core\BedrockBoot.Core.csproj" />
      <ProjectReference Include="..\Round.SDK\Round.SDK\Round.SDK.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Octokit" Version="14.0.0" />
    </ItemGroup>

</Project>
