<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <TargetFrameworks>net10.0-windows10.0.19041.0;net10.0-android</TargetFrameworks>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
        <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
        <RuntimeIdentifier>android-x64</RuntimeIdentifier>

    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0' AND $([MSBuild]::IsOSPlatform('Linux'))">
        <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BedrockBoot.Standard\BedrockBoot.Standard.csproj" />
      <ProjectReference Include="..\PeNet\src\PeNet\PeNet.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Management" Version="11.0.0-preview.1.26104.118" />
      <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.3" />
      <PackageReference Include="Octokit" Version="14.0.0" />
      <PackageReference Include="XUserLauncher.Core" Version="1.0.0.5"/>
    </ItemGroup>

</Project>
