<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BedrockBoot.Base\BedrockBoot.Base.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Management" Version="11.0.0-preview.1.26104.118" />
      <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.3" />
    </ItemGroup>

</Project>
