<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>android-x64</RuntimeIdentifier>

    <Nullable>enable</Nullable>
    <ApplicationId>com.roundstudio.ava</ApplicationId>
    <ApplicationTitle>Ava</ApplicationTitle>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>0.1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="12.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BedrockBoot\BedrockBoot.csproj" />
  </ItemGroup>

</Project>